### ISSUE TITLE
NOISE_BT randomState is Infinity; causes NaN values in decoded data

### ISSUE THREAD

**Issue by phoboslab** [audiocogs/aac.js#10]
This line causes `randomState` to be `Infinity` after a few iterations.
```js
this.randomState *= 1664525 + 1013904223;
```
~ https://github.com/audiocogs/aac.js/blob/master/src/ics.js#L234

A few lines later these "random" values will be multiplied with a scale factor of `-0` (because `energy` is `Infinity` as well), resulting in `NaN`.

Proposed fix, cast it to an integer:
```js
this.randomState = (this.randomState * (1664525 + 1013904223))|0;
```

**Comment by devongovett** [comment]
Sounds good, can you make a pull request?
