### ISSUE TITLE
Question: PCM to AAC Encoder?

### ISSUE THREAD

**Issue by lyricalpolymath** [audiocogs/aac.js#6]
Hello
impressive projects.
this is not really an issue, It's more of a question, maybe a stupid one :)
Is it possible to Encode a PCM from The microphone (captured with getUserMedia) to AAC?
and do this in the browser instead of the server?

Thanks in advance
b

**Comment by crackofdusk** [comment]
Hey @lyricalpolymath 

It's possible, although I'm not aware of any AAC encoders written in JavaScript. One way to do it would be to find an AAC encoder written in C or C++ and compile it to JavaScript using [http://kripken.github.io/emscripten-site/](emscripten).

**Comment by lyricalpolymath** [comment]
thanks @crackofdusk 
I've since moved to other tech...but sense that will have to check back to this in a few months :)
thanks for the tip
